FROM ubuntu:latest

RUN apt-get -y update

RUN apt-get install -y software-properties-common

RUN add-apt-repository -y ppa:ethereum/ethereum

RUN apt-get install -y ethereum

RUN apt-get -y install git

RUN apt-get -y install python3.8

RUN apt-get -y install python3-pip

RUN apt-get -y install libpq-dev

RUN apt-get -y install gcc

WORKDIR /app

COPY . .

RUN pip install -r requirements_bsc.txt --no-use-pep517
