parameters:
  user_prefix: ""

  schema:
    logs: analytics_logs
    staging: analytics_staging
    models: analytics_models
    viz: analytics_viz

  from_prod:

required_credentials:
  - warehouse

default_db: warehouse

presets:

  staging:
    type: autosql
    materialisation: table
    file_name: "{{ task.group }}/{{ task.name }}.sql"
    destination:
      tmp_schema: "{{ schema['staging'] }}"
      schema: "{{ schema['staging'] }}"
      table: "{{ user_prefix }}{{ task.name }}"

  models:
    type: autosql
    materialisation: table
    file_name: "{{ task.group }}/{{ task.name }}.sql"
    destination:
      tmp_schema: "{{ schema['staging'] }}"
      schema: "{{ schema['models'] }}"
      table: "{{ user_prefix }}{{ task.name }}"

  metabase:
    type: autosql
    file_name: "{{ task.group }}/{{ task.name }}.sql"
    materialisation: view
    destination:
      schema: "{{ schema['viz'] }}"
      table: "{{ user_prefix }}{{ task.name[3:] }}"

  create_table:
    type: sql
    file_name: "{{ task.group }}/{{ task.name.split('_')[0] }}_{{ task.name.split('_')[-1] }}.sql"
    parameters:
      schema: "{{ schema['logs'] }}"
      table: "{{ user_prefix }}{{ task.name['create_'|length:] }}"

  copy_from_stage:
    type: sql
    file_name: "{{ task.group }}/copy_from_stage.sql"
    parameters:
      stage: "{{ task.name.split('_')[1] }}_stage"
      schema: "{{ schema['logs'] }}"
      currency: "{{ task.name.split('_')[1] }}"
      table: "{{ task.name.split('_')[-1] }}"
