tasks:

  bsc_incremental_load:
    type: python
    class: blockchain_data.loadData
    parameters:
      file_format: csv_unloading
      stage: bsc_stage
      schema: analytics_logs
      blockchain: bsc
      blockchain_url: 'https://bsc-dataseed.binance.org'
      blocks_per_file: 10000
      max_workers: 10

  update_bsc_blocks:
    preset: copy_from_stage
    parents:
      - bsc_incremental_load
      - create_bsc_blocks

  update_bsc_transactions:
    preset: copy_from_stage
    parents:
      - bsc_incremental_load
      - create_bsc_transactions

  update_bsc_token_transfers:
    preset: copy_from_stage
    parents:
      - bsc_incremental_load
      - create_bsc_token_transfers
    parameters:
      table: token_transfers

  update_bsc_logs:
    preset: copy_from_stage
    parents:
      - bsc_incremental_load
      - create_bsc_logs

  update_bsc_receipts:
    preset: copy_from_stage
    parents:
      - bsc_incremental_load
      - create_bsc_receipts

  update_bsc_contracts:
    preset: copy_from_stage
    parents:
      - bsc_incremental_load
      - create_bsc_contracts

  update_bsc_tokens:
    preset: copy_from_stage
    parents:
      - bsc_incremental_load
      - create_bsc_tokens

  # extract_bq_ethereum_tokens:
  #   preset: extract_bigquery
  #   source:
  #     table: tokens 6738652
  #
  # extract_bq_ethereum_contracts:
  #   preset: extract_bigquery
  #   source:
  #     table: contracts
  #   max_merge_rows: 100000
  #
  # extract_bq_ethereum_blocks:
  #   preset: extract_bigquery
  #   source:
  #     table: blocks
  #   delete_key: hash
  #
  # extract_bq_ethereum_transactions:
  #   preset: extract_bigquery
  #   source:
  #     table: transactions
  #   delete_key: hash
  #   max_merge_rows: 3500000
  #   max_batch_rows: 200000

  # extract_bq_EthereumBlock:
  #   preset: extract_snowflake

  # extract_ethereum_methods:
  #   preset: extract_postgres
  #   source:
  #     table: EthereumMethod
  #   ddl:
  #     columns:
  #       - id
  #       - contract
  #       - "method"
  #       - name: params
  #         type: variant
  #       - "txHash"
  #       - "createdAt"
  #       - "updatedAt"
  #
  # extract_ethereum_transactions:
  #   preset: extract_postgres
  #   source:
  #     table: EthereumTx
  #   ddl:
  #     columns:
  #       - id
  #       - name: "from"
  #         dst_name: "from_address"
  #       - name: "to"
  #         dst_name: "to_address"
  #       - "transactionIndex"
  #       - "gasPrice"
  #       - gas
  #       - "blockNumber"
  #       - hash
  #       - v
  #       - s
  #       - r
  #       - "contractAddress"
  #       - "cumulativeGasUsed"
  #       - "gasUsed"
  #       - logs
  #       - "logsBloom"
  #       - status
  #       - value
  #       - nonce
  #       - "input"
  #       - "balanceTo"
  #       - "balanceFrom"
  #       - "blockHash"
  #       - "createdAt"
  #       - "updatedAt"
  #
  # extract_ethereum_blocks:
  #   preset: extract_postgres
  #   source:
  #     table: EthereumBlock
  #   ddl:
  #     columns:
  #       - id
  #       - difficulty
  #       - "extraData"
  #       - "gasLimit"
  #       - "blockGasUsed"
  #       - hash
  #       - "logsBloom"
  #       - miner
  #       - "mixHash"
  #       - nonce
  #       - "number"
  #       - "parentHash"
  #       - "receiptsRoot"
  #       - "sha3Uncles"
  #       - "stateRoot"
  #       - "timestamp"
  #       - "totalDifficulty"
  #       - "transactionsRoot"
  #       - name: uncles
  #         type: variant
  #       - "createdAt"
  #       - "updatedAt"
  #       - size
  #
  # extract_ethereum_contracts:
  #   preset: extract_postgres
  #   source:
  #     table: EthereumContract
  #   ddl:
  #     columns:
  #       - id
  #       - slug
  #       - address
  #       - type
  #       - network
  #       - name: metadata
  #         type: variant
  #       - createdAt
  #       - updatedAt
