tasks:

  bsc_incremental_load:
    type: python
    class: blockchain_data.loadData
    parameters:
      file_format: csv_unloading
      stage: bsc_stage
      schema: analytics_logs
      blockchain: bsc
      blockchain_url: 'https://bsc-dataseed.binance.org'
      blocks_per_file: 10000
      max_workers: 10

  update_bsc_blocks:
    preset: copy_from_stage
    parents:
      - bsc_incremental_load
      - create_bsc_blocks

  update_bsc_transactions:
    preset: copy_from_stage
    parents:
      - bsc_incremental_load
      - create_bsc_transactions

  update_bsc_token_transfers:
    preset: copy_from_stage
    parents:
      - bsc_incremental_load
      - create_bsc_token_transfers
    parameters:
      table: token_transfers

  update_bsc_logs:
    preset: copy_from_stage
    parents:
      - bsc_incremental_load
      - create_bsc_logs

  update_bsc_receipts:
    preset: copy_from_stage
    parents:
      - bsc_incremental_load
      - create_bsc_receipts

  update_bsc_contracts:
    preset: copy_from_stage
    parents:
      - bsc_incremental_load
      - create_bsc_contracts

  update_bsc_tokens:
    preset: copy_from_stage
    parents:
      - bsc_incremental_load
      - create_bsc_tokens
