tasks:

  extract_ethereum_methods:
    preset: extract_postgres
    source:
      table: EthereumMethod
    ddl:
      columns:
        - id
        - contract
        - "method"
        - name: params
          type: variant
        - "txHash"
        - "createdAt"
        - "updatedAt"

  extract_ethereum_transactions:
    preset: extract_postgres
    source:
      table: EthereumTx
    ddl:
      columns:
        - id
        - name: "from"
          dst_name: "from_address"
        - name: "to"
          dst_name: "to_address"
        - "transactionIndex"
        - "gasPrice"
        - gas
        - "blockNumber"
        - hash
        - v
        - s
        - r
        - "contractAddress"
        - "cumulativeGasUsed"
        - "gasUsed"
        - logs
        - "logsBloom"
        - status
        - value
        - nonce
        - "input"
        - "balanceTo"
        - "balanceFrom"
        - "blockHash"
        - "createdAt"
        - "updatedAt"

  extract_ethereum_blocks:
    preset: extract_postgres
    source:
      table: EthereumBlock
    ddl:
      columns:
        - id
        - difficulty
        - "extraData"
        - "gasLimit"
        - "blockGasUsed"
        - hash
        - "logsBloom"
        - miner
        - "mixHash"
        - nonce
        - "number"
        - "parentHash"
        - "receiptsRoot"
        - "sha3Uncles"
        - "stateRoot"
        - "timestamp"
        - "totalDifficulty"
        - "transactionsRoot"
        - name: uncles
          type: variant
        - "createdAt"
        - "updatedAt"
        - size

  extract_ethereum_contracts:
    preset: extract_postgres
    source:
      table: EthereumContract
    ddl:
      columns:
        - id
        - slug
        - address
        - type
        - network
        - name: metadata
          type: variant
        - createdAt
        - updatedAt
