tasks:

  eth_missing_data_load:
    preset: chain_data_load
    class: blockchain_data_reload.LoadData
    parameters:
      blocks_per_file: 500
      is_archive: true
    parents:
      - create_eth_blocks

  eth_incremental_load:
    preset: chain_data_load
    parameters:
      is_archive: true
    parents:
      - eth_missing_data_load
      - create_eth_blocks

  update_eth_blocks:
    preset: copy_from_stage
    parents:
      - eth_incremental_load
      - create_eth_blocks

  update_eth_transactions:
    preset: copy_from_stage
    parents:
      - eth_incremental_load
      - create_eth_transactions

  update_eth_token_transfers:
    preset: copy_from_stage
    parameters:
      table: token_transfers
    parents:
      - eth_incremental_load
      - create_eth_token_transfers

  update_eth_logs:
    preset: copy_from_stage
    parents:
      - eth_incremental_load
      - create_eth_logs

  update_eth_receipts:
    preset: copy_from_stage
    parents:
      - eth_incremental_load
      - create_eth_receipts

  update_eth_contracts:
    preset: copy_from_stage
    parents:
      - eth_incremental_load
      - create_eth_contracts

  update_eth_tokens:
    preset: copy_from_stage
    parents:
      - eth_incremental_load
      - create_eth_tokens

  update_eth_geth_traces:
    preset: copy_from_stage
    parameters:
      table: geth_traces
    parents:
      - eth_incremental_load
      - create_eth_geth_traces
