tasks:

  stg_xwg_daily_token_supply_delta:
    preset: staging
    parents:
      - f_bsc_holder_balances

  stg_xwg_new_holders:
    preset: staging
    parents:
      - f_bsc_nft_sales

  f_xwg_token_distribution_all_time:
    preset: models
    parents:
      - f_bsc_holder_balances

  f_xwg_token_distribution:
    preset: models
    parents:
      - stg_xwg_daily_token_supply_delta
      - f_xwg_token_distribution_all_time

  f_xwg_total_dreamcard_holders:
    preset: models
    parents:
      - f_bsc_holder_balances

  f_xwg_total_dreamcard_volume:
    preset: models
    parents:
      - f_bsc_nft_sales

  f_xwg_total_dreamcards_released:
    preset: models
    parents:
      - update_bsc_token_transfers
      - update_bsc_blocks

  f_xwg_total_xwg_holders:
    preset: models
    parents:
      - f_bsc_holder_balances

  f_xwg_new_wallet_addresses:
    preset: models
    parents:
      - stg_xwg_new_holders
