presets:
    # For hard-coded address tables, like stg_bsc_internal_xwg_addresses
    address_table:
      type: autosql
      materialisation: table
      file_name: "xwg/address_table.sql"
      destination:
        tmp_schema: "{{ schema['staging'] }}"
        schema: "{{ schema['staging'] }}"
        table: "{{ user_prefix }}{{ task.name }}"

tasks:

  # ERC20 tokens we are interested in for holder analysis
  stg_bsc_holders_erc20_tokens:
    preset: address_table
    parameters:
      addresses:
        - "'0x6b23c89196deb721e6fd9726e6c76e4810a464bc'"

  # ERC721 tokens we are interested in for holder analysis
  stg_bsc_holders_erc721_tokens:
    preset: address_table
    parameters:
      addresses:
        - "'0xe6965b4f189dbdb2bd65e60abaeb531b6fe9580b'"

  # Holding addresses which are owned by XWG so we can exclude
  stg_bsc_xwg_addresses_to_exclude:
    preset: address_table
    parameters:
      addresses:
        - "'0xe6965b4f189dbdb2bd65e60abaeb531b6fe9580b'"
        - "'0xe59e1b014895518b3815eb2845234d4844bc697c'"
        - "'0xd1290e043305678c64415a28dcba1a46c52392b8'"
        - "'0x7b44c5891e2ac1e4e8757221066fbbb4cf19b74b'"
        - "'0x61c41e8d095df1036d1af9f7e8961ec7409dd2c6'"
        - "'0x6d7e4dda59604652ead3f82932f00e7bd7205bfe'"
        - "'0x3041d6b41caca2b5321fe3616f576a5108515a8e'"
        - "'0x88881808f5c6c0b25d5f4c2523e3948c33857013'"
        - "'0x88d42e8b4f79c1fa813b4565728f7f9e258f9c06'"
        - "'0x2493c3ac0b3cc1432b897b71ab9803f891df40c8'"
        - "'0x53005ae133139eaef5baea1be021d000712b827e'"
        - "'0x48931b205a2d505ec485ab4e6c253ac2f243f526'"
        - "'0x0fe2737b878c83fe5cb0ba17b3542df671f8cfee'"
        - "'0x14ac8851f509b75bf596d7ea5418d7daaf637d99'"
        - "'0x1737e635e7b38f6a0299517f042fba43d84f090c'"
        - "'0xd2edcaaafce4a1b526f30fcc87e91502f77e6c4c'"
        - "'0x518a9cc532d5b8a9c50212c2d6d9cfa743e92926'"
        - "'0x27e636d95fda95064abdd7d31dffca4b41f9cb44'"
        - "'0x777784eca6df4831d77971a379d1fe443da39373'"
        - "'0xbde30b04bb5cce5808f225e46aa069957d0c8efd'"
        - "'0x1ee6539c12361b6bc1fb930435c70d557dee392f'"
        - "'0x0cbcfb2b092f314a7360ff5de61676c5d0d4848c'"
        - "'0xc061a008d5a5df8487ed90e8ec78d89d85be058f'"

  # Payment tokens considered for NFT sales metrics
  stg_bsc_nft_sale_payment_tokens:
    preset: address_table
    parameters:
      addresses:
        - "'0x6b23c89196deb721e6fd9726e6c76e4810a464bc'"

  # NFT tokens considered for NFT sales metrics
  stg_bsc_nft_sale_nft_tokens:
    preset: address_table
    parameters:
      addresses:
        - "'0xe6965b4f189dbdb2bd65e60abaeb531b6fe9580b'"

  stg_bsc_holder_balances:
    preset: staging
    parents:
      - stg_bsc_holders_erc20_tokens
      - stg_bsc_holders_erc721_tokens
      - stg_bsc_xwg_addresses_to_exclude
      - update_bsc_token_transfers
      - update_bsc_blocks

  f_bsc_nft_sales:
    preset: models
    parents:
      - stg_bsc_nft_sale_nft_tokens
      - stg_bsc_nft_sale_payment_tokens
      - update_bsc_token_transfers
      - update_bsc_blocks

  f_bsc_circulating_supply:
    preset: models
    parents:
      - stg_bsc_holder_balances
      - stg_dates

  f_bsc_holder_balances:
    preset: models
    parents:
      - stg_bsc_holder_balances
      - f_bsc_circulating_supply

  f_bsc_daily_holders_count:
    preset: models
    parents:
      - f_bsc_holder_balances
      - stg_dates

  f_bsc_daily_active_traders:
    preset: models
    parents:
      - f_bsc_nft_sales
